create database quiz;
use quiz;
set global time_zone = '+1:00';	
create table fragen(nr int primary key,frage varchar(128),antwort smallint,m1 varchar(64),m2 varchar(64),m3 varchar(64));

insert into fragen values(1,'Wie alt ist die Erde?',1,'ca 44.55 Mia','ca 63.55 Mia','genau 44.55 Mia');
insert into fragen values(2,'Welchen Durchmesser hat die Erde?',3,'12713km','10900km','23980km');
insert into fragen values(3,'Wie viele Menschen leben auf der Erde?',3,'8.2 Mrd.','6.8 Mrd.','7.5 Mrd.');
insert into fragen values(4,'Wo liegt Argentinien?',2,'In Asien','In Südamerika','In Europa');
insert into fragen values(5,'Was macht ein Informatiker?',2,'tanzen','programmieren','springen');
insert into fragen values(6,'Wie hoch ist die durchschnittliche Lebenserwartung in "Bella Italia"?',2,'75','80','85');
insert into fragen values(7,'Wie heißt der längste Fluss, der durch China fließt? ',1,'Jangtsekiang','Mekong','Xi Jiang');
insert into fragen values(8,'Wie viele Wassertropfen füllen einen Teelöffel?',2,'75','120','50');
insert into fragen values(9,'Welches Land liegt am dichtesten an Nigeria dran?',3,'Iran','Madagaskar','Frankreich');
insert into fragen values(10,'Welches dieser Länder hat die Hauptstadt mit den meisten Einwohnern?',3,'Angola','Iran','Kolumbien');
insert into fragen values(11,'Welche Stadt gibt es wirklich?',1,'Saint-Luis-du-Ha!Ha!','Superman','PemPlem');
insert into fragen values(12,'Mit welchem Wunsch begrüßen sich die Bergleute ?',2,'Grüss Gott','Glück auf!','Guten Tag!');
insert into fragen values(13,'Wie viel Karten hat ein Skatspiel?',1,'32','45','26');
insert into fragen values(14,'Die längste Praline der Welt?',2,'Bounty','Duplo','Mars');
insert into fragen values(15,'Wer betrat 1969 als erster Mensch den Mond?',4,'Chuck Norris','Richard Nixon','Neil Armweak');
insert into fragen values(16,'Wer war der Kommandant von Apollo 11?',1,'Neil Armstrong','Mao Tse Tung','Der Papst');
insert into fragen values(17,'Wie viele Nasenlöcher hat ein Pottwal?',1,'1','2','3');		
insert into fragen values(18,'Auf welchem Platz liegt die durchschnittliche Lebenserwartung der Schweiz?',3,'3. Platz','1. Platz','6. Platz');
insert into fragen values(19,'Was bedeutet SMS?',2,'Send Message Service','Short Message Service','Send my Snap');	
insert into fragen values(20,'Wann blüht der Kakaobaum?',2,'Im Sommer','Das ganze Jahr über','Im Herbst');
insert into fragen values(21,'Was ist Rauschgold?',2,'Fake Gold','Schäumendes Gold','ein dünnes Messingblech');		
insert into fragen values(22,'Welcher Teil von Iperka wird oft vernachlässigt?',3,'Planen','Realisieren','Informieren');
insert into fragen values(23,'Was bedeutet USA?',2,'Union States of America','Unitet States of America','Unitet States America');
drop table bilder;
create table bilder(nr int primary key, url varchar(64));

insert into bilder values(1,'1,erde.png');
insert into bilder values(2,'2,durchmesser.png');
insert into bilder values(3,'3,menschen.png');
insert into bilder values(4,'4, arg.png');
insert into bilder values(5,'5, info.png');
insert into bilder values(6,'6,life.png');
insert into bilder values(7,'7,fluss.png');
insert into bilder values(8,'8,tropfen.png');
insert into bilder values(9,'9, nigeria.png');
insert into bilder values(10,'10,einwohner.png');
insert into bilder values(11,'stadt.png');
insert into bilder values(12,'berg.png');
insert into bilder values(13,'karten.png');
insert into bilder values(14,'praliene.png');
insert into bilder values(15,'mond.png');
insert into bilder values(16,'apollo.png');
insert into bilder values(17,'wal.png');
insert into bilder values(18,'schweiz.png');
insert into bilder values(19,'sms.png');
insert into bilder values(20,'kakao.png');
insert into bilder values(21,'gold.png');
insert into bilder values(22,'iperka.png');
insert into bilder values(23,'usa.png');
